package beans;
// Generated 02.12.2013 21:24:12 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Avto generated by hbm2java
 */
@Entity
@Table(name = "avto", schema = "public")
public class Avto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5275153500125204246L;
	private int avtoid;
	private String color;
	private String enginenumber;
	private Integer godvip;
	private String model;
	private String statenumber;
	private String techpassportseria;
	private Date techpassportdata;
	private String techpassportvidan;
	private Integer garazhnumber;
	private String gsmMarka;
	private Date datalastto;
	private Date datanextto;
	private Set<Drivingschedule> drivingschedules = new HashSet<Drivingschedule>(
			0);

	public Avto() {
	}


	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="avto_avtoid_seq", name="avto_avtoid_seq")
	@GeneratedValue(generator="avto_avtoid_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "AVTOID", nullable = false)
	public int getAvtoid() {
		return this.avtoid;
	}

	public void setAvtoid(int avtoid) {
		this.avtoid = avtoid;
	}

	@Column(name = "COLOR", nullable = false)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "ENGINENUMBER", nullable = false, length = 30)
	public String getEnginenumber() {
		return this.enginenumber;
	}

	public void setEnginenumber(String enginenumber) {
		this.enginenumber = enginenumber;
	}

	@Column(name = "GODVIP", nullable = false)
	public int getGodvip() {
		return this.godvip;
	}

	public void setGodvip(int godvip) {
		this.godvip = godvip;
	}

	@Column(name = "MODEL", nullable = false, length = 30)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "STATENUMBER", nullable = false, length = 30)
	public String getStatenumber() {
		return this.statenumber;
	}

	public void setStatenumber(String statenumber) {
		this.statenumber = statenumber;
	}

	@Column(name = "TECHPASSPORTSERIA", nullable = false)
	public String getTechpassportseria() {
		return this.techpassportseria;
	}

	public void setTechpassportseria(String techpassportseria) {
		this.techpassportseria = techpassportseria;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "TECHPASSPORTDATA", nullable = false, length = 13)
	public Date getTechpassportdata() {
		return this.techpassportdata;
	}

	public void setTechpassportdata(Date techpassportdata) {
		this.techpassportdata = techpassportdata;
	}

	@Column(name = "TECHPASSPORTVIDAN", nullable = false, length = 30)
	public String getTechpassportvidan() {
		return this.techpassportvidan;
	}

	public void setTechpassportvidan(String techpassportvidan) {
		this.techpassportvidan = techpassportvidan;
	}

	@Column(name = "GARAZHNUMBER", nullable = false)
	public int getGarazhnumber() {
		return this.garazhnumber;
	}

	public void setGarazhnumber(int garazhnumber) {
		this.garazhnumber = garazhnumber;
	}

	@Column(name = "GSM_MARKA", nullable = false, length = 10)
	public String getGsmMarka() {
		return this.gsmMarka;
	}

	public void setGsmMarka(String gsmMarka) {
		this.gsmMarka = gsmMarka;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "datalastto", length = 13)
	public Date getDatalastto() {
		return this.datalastto;
	}

	public void setDatalastto(Date datalastto) {
		this.datalastto = datalastto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datanextto", length = 13)
	public Date getDatanextto() {
		return this.datanextto;
	}

	public void setDatanextto(Date datanextto) {
		this.datanextto = datanextto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "avto")
	public Set<Drivingschedule> getDrivingschedules() {
		return this.drivingschedules;
	}

	public void setDrivingschedules(Set<Drivingschedule> drivingschedules) {
		this.drivingschedules = drivingschedules;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return model;
	}

}
