package beans;

// Generated 12.12.2013 21:23:38 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", schema = "public")
public class Categories implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4339110551278812306L;
	private int kategoriesid;
	private String kategoriesName;
	private int timeTheory;
	private int timePractice;
	private int costEducation;
	private Set<Groups> groupses = new HashSet<Groups>(0);

	public Categories() {
	}

	public Categories( String kategoriesName, int timeTheory,
			int timePractice, int costEducation) {
		this.kategoriesName = kategoriesName;
		this.timeTheory = timeTheory;
		this.timePractice = timePractice;
		this.costEducation = costEducation;
	}

	public Categories(int kategoriesid, String kategoriesName, int timeTheory,
			int timePractice, int costEducation, Set<Groups> groupses) {
		this.kategoriesid = kategoriesid;
		this.kategoriesName = kategoriesName;
		this.timeTheory = timeTheory;
		this.timePractice = timePractice;
		this.costEducation = costEducation;
		this.groupses = groupses;
	}

	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="kategories_kategoriesid_seq", name="kategories_kategoriesid_seq")
	@GeneratedValue(generator="kategories_kategoriesid_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "kategoriesid", unique = true, nullable = false)
	public int getKategoriesid() {
		return this.kategoriesid;
	}

	public void setKategoriesid(int kategoriesid) {
		this.kategoriesid = kategoriesid;
	}

	@Column(name = "kategories_name", nullable = false, length = 30)
	public String getKategoriesName() {
		return this.kategoriesName;
	}

	public void setKategoriesName(String kategoriesName) {
		this.kategoriesName = kategoriesName;
	}

	@Column(name = "time_theory", nullable = false)
	public int getTimeTheory() {
		return this.timeTheory;
	}

	public void setTimeTheory(int timeTheory) {
		this.timeTheory = timeTheory;
	}

	@Column(name = "time_practice", nullable = false)
	public int getTimePractice() {
		return this.timePractice;
	}

	public void setTimePractice(int timePractice) {
		this.timePractice = timePractice;
	}

	@Column(name = "cost_education", nullable = false)
	public int getCostEducation() {
		return this.costEducation;
	}

	public void setCostEducation(int costEducation) {
		this.costEducation = costEducation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	public Set<Groups> getGroupses() {
		return this.groupses;
	}

	public void setGroupses(Set<Groups> groupses) {
		this.groupses = groupses;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return kategoriesName;
	}

}
