package beans;

// Generated 12.12.2013 21:23:38 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", schema = "public")
public class Groups implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3192648564016427292L;
	private int groupid;
	private Categories categories;
	private Educationtypes educationtypes;
	private YearOfEducation yearOfEducation;
	private Date gruopstartdate;
	private Date groupenddate;
	private String pricazn;
	private Date pricazdata;
	private String groupName;
	private String flagZakr;
	private Set<Students> studentses = new HashSet<Students>(0);
	private Set<Schedules> scheduleses = new HashSet<Schedules>(0);

	public Groups() {
	}

	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="group_groupid_seq", name="group_groupid_seq")
	@GeneratedValue(generator="group_groupid_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "groupid", unique = true, nullable = false)
	public int getGroupid() {
		return this.groupid;
	}

	public void setGroupid(int groupid) {
		this.groupid = groupid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "katid", nullable = false)
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "formeducationid", nullable = false)
	public Educationtypes getEducationtypes() {
		return this.educationtypes;
	}

	public void setEducationtypes(Educationtypes educationtypes) {
		this.educationtypes = educationtypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "year_of_education_id")
	public YearOfEducation getYearOfEducation() {
		return this.yearOfEducation;
	}

	public void setYearOfEducation(YearOfEducation yearOfEducation) {
		this.yearOfEducation = yearOfEducation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "gruopstartdate", nullable = false, length = 13)
	public Date getGruopstartdate() {
		return this.gruopstartdate;
	}

	public void setGruopstartdate(Date gruopstartdate) {
		this.gruopstartdate = gruopstartdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "groupenddate", length = 13)
	public Date getGroupenddate() {
		return this.groupenddate;
	}

	public void setGroupenddate(Date groupenddate) {
		this.groupenddate = groupenddate;
	}
	
	@Column(name = "flag_zakr")
	public String getFlagZakr() {
		return this.flagZakr;
	}

	public void setFlagZakr(String flagZakr) {
		this.flagZakr = flagZakr;
	}

	@Column(name = "pricazn", length = 10)
	public String getPricazn() {
		return this.pricazn;
	}

	public void setPricazn(String pricazn) {
		this.pricazn = pricazn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pricazdata", length = 13)
	public Date getPricazdata() {
		return this.pricazdata;
	}

	public void setPricazdata(Date pricazdata) {
		this.pricazdata = pricazdata;
	}

	@Column(name = "group_name", nullable = false)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<Students> getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set<Students> studentses) {
		this.studentses = studentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<Schedules> getScheduleses() {
		return this.scheduleses;
	}

	public void setScheduleses(Set<Schedules> scheduleses) {
		this.scheduleses = scheduleses;
	}
	@Override
	public String toString() {
		return groupName;
	}

}
