package beans;

// Generated 11.01.2014 22:50:07 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LinkTeacherSubject generated by hbm2java
 */
@Entity
@Table(name = "link_teacher_subject", schema = "public")
public class LinkTeacherSubject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1296684839491777624L;
	private int id;
	private Teachers teachers;
	private Subjects subjects;

	public LinkTeacherSubject() {
	}

	public LinkTeacherSubject(int id, Teachers teachers, Subjects subjects) {
		this.id = id;
		this.teachers = teachers;
		this.subjects = subjects;
	}

	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="link_teacher_subject_id_seq", name="link_teacher_subject_id_seq")
	@GeneratedValue(generator="link_teacher_subject_id_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public Teachers getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Teachers teachers) {
		this.teachers = teachers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subjects getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Subjects subjects) {
		this.subjects = subjects;
	}

}
