package beans;
// Generated 02.12.2013 21:28:10 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Schedules generated by hbm2java
 */
@Entity
@Table(name = "schedules", schema = "public")
public class Schedules implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2516257648880095317L;
	private int scheduleId;
	private Groups groups;
	private Themes themes;
	private Teachers teachers;
	private Date beginTime;
	private Date endTime;

	public Schedules() {
	}

	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="schedule_schedule_id_seq", name="schedule_schedule_id_seq")
	@GeneratedValue(generator="schedule_schedule_id_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "SCHEDULE_ID", nullable = false)
	public int getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(int scheduleId) {
		this.scheduleId = scheduleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUP_ID", nullable = false)
	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "THEME_ID", nullable = false)
	public Themes getThemes() {
		return this.themes;
	}

	public void setThemes(Themes themes) {
		this.themes = themes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEACHER_ID", nullable = false)
	public Teachers getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Teachers teachers) {
		this.teachers = teachers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BEGIN_TIME", length = 13)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_TIME", length = 13)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}


}
