package beans;

// Generated 11.12.2013 23:12:53 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name = "students", schema = "public")
public class Students implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7105420408927689908L;
	private int idstudent;
	private TypeEducation typeEducation;
	private Groups groups;
	private Users users;
	private String surname;
	private String name;
	private String patronymicname;
	private Date datebirth;
	private String birthplace;
	private String docseries;
	private String docnumber;
	private Date docdate;
	private String doinfo;
	private String address;
	private String educationinfo;
	private String jobplace;
	private String phone;
	private String pol;
	private Date ekzData;
	private String otchislen;
	private String ekzFlag;
	private Date dataOtchisl;
	private String noteOtchislen;
	private String typeDocum;
	private String svidInfo;
	private Set<Tests> testses = new HashSet<Tests>(0);
	private Set<Drivingschedule> drivingschedules = new HashSet<Drivingschedule>(
			0);

	public Students() {
	}

	/*public Students(int idstudent, TypeEducation typeEducation, Groups groups,
			String surname, String name, String patronymicname, Date datebirth,
			String birthplace, String docnumber, Date docdate, String address,
			String educationinfo, String phone) {
		this.idstudent = idstudent;
		this.typeEducation = typeEducation;
		this.groups = groups;
		this.surname = surname;
		this.name = name;
		this.patronymicname = patronymicname;
		this.datebirth = datebirth;
		this.birthplace = birthplace;
		this.docnumber = docnumber;
		this.docdate = docdate;
		this.address = address;
		this.educationinfo = educationinfo;
		this.phone = phone;
	}

	public Students(int idstudent, TypeEducation typeEducation, Groups groups,
			String surname, String name, String patronymicname, Date datebirth,
			String birthplace, String docseries, String docnumber,
			Date docdate, String doinfo, String address, String educationinfo,
			String jobplace, String phone, String pol, Set<Tests> testses,
			Set<Drivingschedule> drivingschedules) {
		this.idstudent = idstudent;
		this.typeEducation = typeEducation;
		this.groups = groups;
		this.surname = surname;
		this.name = name;
		this.patronymicname = patronymicname;
		this.datebirth = datebirth;
		this.birthplace = birthplace;
		this.docseries = docseries;
		this.docnumber = docnumber;
		this.docdate = docdate;
		this.doinfo = doinfo;
		this.address = address;
		this.educationinfo = educationinfo;
		this.jobplace = jobplace;
		this.phone = phone;
		this.pol = pol;
		this.testses = testses;
		this.drivingschedules = drivingschedules;
	}*/

	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="students_idstudent_seq", name="students_idstudent_seq")
	@GeneratedValue(generator="students_idstudent_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "idstudent", unique = true)
	public int getIdstudent() {
		return this.idstudent;
	}

	public void setIdstudent(int idstudent) {
		this.idstudent = idstudent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "educationtypeid")
	public TypeEducation getTypeEducation() {
		return this.typeEducation;
	}

	public void setTypeEducation(TypeEducation typeEducation) {
		this.typeEducation = typeEducation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupid")
	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "surname", nullable = false, length = 30)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "patronymicname",  length = 30)
	public String getPatronymicname() {
		return this.patronymicname;
	}

	public void setPatronymicname(String patronymicname) {
		this.patronymicname = patronymicname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datebirth",  length = 13)
	public Date getDatebirth() {
		return this.datebirth;
	}

	public void setDatebirth(Date datebirth) {
		this.datebirth = datebirth;
	}

	@Column(name = "birthplace")
	public String getBirthplace() {
		return this.birthplace;
	}

	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	@Column(name = "docseries", length = 10)
	public String getDocseries() {
		return this.docseries;
	}

	public void setDocseries(String docseries) {
		this.docseries = docseries;
	}

	@Column(name = "docnumber", length = 10)
	public String getDocnumber() {
		return this.docnumber;
	}

	public void setDocnumber(String docnumber) {
		this.docnumber = docnumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "docdate", length = 13)
	public Date getDocdate() {
		return this.docdate;
	}

	public void setDocdate(Date docdate) {
		this.docdate = docdate;
	}

	@Column(name = "doinfo")
	public String getDoinfo() {
		return this.doinfo;
	}

	public void setDoinfo(String doinfo) {
		this.doinfo = doinfo;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "educationinfo")
	public String getEducationinfo() {
		return this.educationinfo;
	}

	public void setEducationinfo(String educationinfo) {
		this.educationinfo = educationinfo;
	}

	@Column(name = "jobplace")
	public String getJobplace() {
		return this.jobplace;
	}

	public void setJobplace(String jobplace) {
		this.jobplace = jobplace;
	}

	@Column(name = "phone",  length = 30)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "pol", length = 1)
	public String getPol() {
		return this.pol;
	}

	public void setPol(String pol) {
		this.pol = pol;
	}
	@Column(name = "ekzFlag")
	public String getEkzFlag() {
		return this.ekzFlag;
	}

	public void setEkzFlag(String ekzFlag) {
		this.ekzFlag = ekzFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ekzData", length = 13)
	public Date getEkzData() {
		return this.ekzData;
	}

	public void setEkzData(Date ekzData) {
		this.ekzData = ekzData;
	}

	@Column(name = "otchislen")
	public String getOtchislen() {
		return this.otchislen;
	}

	public void setOtchislen(String otchislen) {
		this.otchislen = otchislen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataOtchisl", length = 13)
	public Date getDataOtchisl() {
		return this.dataOtchisl;
	}

	public void setDataOtchisl(Date dataOtchisl) {
		this.dataOtchisl = dataOtchisl;
	}

	@Column(name = "noteOtchislen")
	public String getNoteOtchislen() {
		return this.noteOtchislen;
	}

	public void setNoteOtchislen(String noteOtchislen) {
		this.noteOtchislen = noteOtchislen;
	}
	
	@Column(name = "type_docum")
	public String getTypeDocum() {
		return this.typeDocum;
	}

	public void setTypeDocum(String typeDocum) {
		this.typeDocum = typeDocum;
	}
	
	@Column(name = "svid_info")
	public String getSvidInfo() {
		return this.svidInfo;
	}

	public void setSvidInfo(String svidInfo) {
		this.svidInfo = svidInfo;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<Tests> getTestses() {
		return this.testses;
	}

	public void setTestses(Set<Tests> testses) {
		this.testses = testses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<Drivingschedule> getDrivingschedules() {
		return this.drivingschedules;
	}

	public void setDrivingschedules(Set<Drivingschedule> drivingschedules) {
		this.drivingschedules = drivingschedules;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return surname + " " + name;
	}

}
