package beans;
// Generated 02.12.2013 21:28:10 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teachers generated by hbm2java
 */
@Entity
@Table(name = "teachers", schema = "public")
public class Teachers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4280783792327444909L;
	private int prepodid;
	private TypeEducation typeEducation;
	private TypeTeacher typeTeacher;
	private String prepodfam;
	private String prepodim;
	private String prepodot;
	private Date birthdate;
	private String birthplace;
	private String address;
	private String phone;
	private String pravan;
	private Date pravadata;
	private String pravavidano;
	private String pravakat;
	private String uchzavedenie;
	private int godokonchaniya;
	private String diplomseria;
	private int voditstazh;
	private boolean uvolen;
	private String uvolinfo;
	private Set<Drivingschedule> drivingschedules = new HashSet<Drivingschedule>(
			0);
	private Set<Schedules> scheduleses = new HashSet<Schedules>(0);
	private Set<LinkTeacherSubject> linkTeacherSubjects = new HashSet<LinkTeacherSubject>(
			0);

	public Teachers() {
	}

	/*public Teachers(int prepodid, TypeEducation typeEducation,
			TypeTeacher typeTeacher, String prepodfam, String prepodim,
			String prepodot, Date birthdate, Serializable pol,
			String birthplace, String address, String phone, String pravan,
			Date pravadata, String pravavidano, String pravakat,
			String specpodiplomu, String uchzavedenie, int godokonchaniya,
			String diplomseria, int voditstazh, boolean uvolen, String uvolinfo) {
		this.prepodid = prepodid;
		this.typeEducation = typeEducation;
		this.typeTeacher = typeTeacher;
		this.prepodfam = prepodfam;
		this.prepodim = prepodim;
		this.prepodot = prepodot;
		this.birthdate = birthdate;
		this.birthplace = birthplace;
		this.address = address;
		this.phone = phone;
		this.pravan = pravan;
		this.pravadata = pravadata;
		this.pravavidano = pravavidano;
		this.pravakat = pravakat;
		this.specpodiplomu = specpodiplomu;
		this.uchzavedenie = uchzavedenie;
		this.godokonchaniya = godokonchaniya;
		this.diplomseria = diplomseria;
		this.voditstazh = voditstazh;
		this.uvolen = uvolen;
		this.uvolinfo = uvolinfo;
	}

	public Teachers(int prepodid, TypeEducation typeEducation,
			TypeTeacher typeTeacher, String prepodfam, String prepodim,
			String prepodot, Date birthdate, Serializable pol,
			String birthplace, String address, String phone, String pravan,
			Date pravadata, String pravavidano, String pravakat,
			String specpodiplomu, String uchzavedenie, int godokonchaniya,
			String diplomseria, int voditstazh, boolean uvolen,
			String uvolinfo, Set<Drivingschedule> drivingschedules,
			Set<Schedules> scheduleses) {
		this.prepodid = prepodid;
		this.typeEducation = typeEducation;
		this.typeTeacher = typeTeacher;
		this.prepodfam = prepodfam;
		this.prepodim = prepodim;
		this.prepodot = prepodot;
		this.birthdate = birthdate;
		this.pol = pol;
		this.birthplace = birthplace;
		this.address = address;
		this.phone = phone;
		this.pravan = pravan;
		this.pravadata = pravadata;
		this.pravavidano = pravavidano;
		this.pravakat = pravakat;
		this.specpodiplomu = specpodiplomu;
		this.uchzavedenie = uchzavedenie;
		this.godokonchaniya = godokonchaniya;
		this.diplomseria = diplomseria;
		this.voditstazh = voditstazh;
		this.uvolen = uvolen;
		this.uvolinfo = uvolinfo;
		this.drivingschedules = drivingschedules;
		this.scheduleses = scheduleses;
	}*/

	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="prepod_prepodid_seq", name="prepod_prepodid_seq")
	@GeneratedValue(generator="prepod_prepodid_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "PREPODID", nullable = false)
	public int getPrepodid() {
		return this.prepodid;
	}

	public void setPrepodid(int prepodid) {
		this.prepodid = prepodid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TYPE_EDUCATION", nullable = false)
	public TypeEducation getTypeEducation() {
		return this.typeEducation;
	}

	public void setTypeEducation(TypeEducation typeEducation) {
		this.typeEducation = typeEducation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PREPOD_MASTER_ID", nullable = false)
	public TypeTeacher getTypeTeacher() {
		return this.typeTeacher;
	}

	public void setTypeTeacher(TypeTeacher typeTeacher) {
		this.typeTeacher = typeTeacher;
	}

	@Column(name = "PREPODFAM", length = 35)
	public String getPrepodfam() {
		return this.prepodfam;
	}

	public void setPrepodfam(String prepodfam) {
		this.prepodfam = prepodfam;
	}

	@Column(name = "PREPODIM", length = 35)
	public String getPrepodim() {
		return this.prepodim;
	}

	public void setPrepodim(String prepodim) {
		this.prepodim = prepodim;
	}

	@Column(name = "PREPODOT", length = 35)
	public String getPrepodot() {
		return this.prepodot;
	}

	public void setPrepodot(String prepodot) {
		this.prepodot = prepodot;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTHDATE", length = 13)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}


	@Column(name = "BIRTHPLACE")
	public String getBirthplace() {
		return this.birthplace;
	}

	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	@Column(name = "ADDRESS", length = 150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PHONE", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "PRAVAN", length = 30)
	public String getPravan() {
		return this.pravan;
	}

	public void setPravan(String pravan) {
		this.pravan = pravan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRAVADATA", length = 13)
	public Date getPravadata() {
		return this.pravadata;
	}

	public void setPravadata(Date pravadata) {
		this.pravadata = pravadata;
	}

	@Column(name = "PRAVAVIDANO", length = 100)
	public String getPravavidano() {
		return this.pravavidano;
	}

	public void setPravavidano(String pravavidano) {
		this.pravavidano = pravavidano;
	}

	@Column(name = "PRAVAKAT")
	public String getPravakat() {
		return this.pravakat;
	}

	public void setPravakat(String pravakat) {
		this.pravakat = pravakat;
	}

	@Column(name = "UCHZAVEDENIE", length = 250)
	public String getUchzavedenie() {
		return this.uchzavedenie;
	}

	public void setUchzavedenie(String uchzavedenie) {
		this.uchzavedenie = uchzavedenie;
	}

	@Column(name = "GODOKONCHANIYA")
	public int getGodokonchaniya() {
		return this.godokonchaniya;
	}

	public void setGodokonchaniya(int godokonchaniya) {
		this.godokonchaniya = godokonchaniya;
	}

	@Column(name = "DIPLOMSERIA", length = 50)
	public String getDiplomseria() {
		return this.diplomseria;
	}

	public void setDiplomseria(String diplomseria) {
		this.diplomseria = diplomseria;
	}

	@Column(name = "VODITSTAZH")
	public int getVoditstazh() {
		return this.voditstazh;
	}

	public void setVoditstazh(int voditstazh) {
		this.voditstazh = voditstazh;
	}

	@Column(name = "UVOLEN")
	public boolean isUvolen() {
		return this.uvolen;
	}

	public void setUvolen(boolean uvolen) {
		this.uvolen = uvolen;
	}

	@Column(name = "UVOLINFO", length = 50)
	public String getUvolinfo() {
		return this.uvolinfo;
	}

	public void setUvolinfo(String uvolinfo) {
		this.uvolinfo = uvolinfo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teachers")
	public Set<Drivingschedule> getDrivingschedules() {
		return this.drivingschedules;
	}

	public void setDrivingschedules(Set<Drivingschedule> drivingschedules) {
		this.drivingschedules = drivingschedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teachers")
	public Set<Schedules> getScheduleses() {
		return this.scheduleses;
	}

	public void setScheduleses(Set<Schedules> scheduleses) {
		this.scheduleses = scheduleses;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teachers")
	public Set<LinkTeacherSubject> getLinkTeacherSubjects() {
		return this.linkTeacherSubjects;
	}

	public void setLinkTeacherSubjects(
			Set<LinkTeacherSubject> linkTeacherSubjects) {
		this.linkTeacherSubjects = linkTeacherSubjects;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return prepodfam+ " " + prepodim + " " + prepodot;
	}

}
