package beans;
// Generated 02.12.2013 21:28:10 by Hibernate Tools 4.0.0

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tests generated by hbm2java
 */
@Entity
@Table(name = "tests", schema = "public")
public class Tests implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4010404272243552270L;
	private int testId;
	private Students students;
	private Themes themes;
	private String typeOfTest;
	private Timestamp timeOfTest;
	private String mark;
	private Double ball;

	public Tests() {
	}

	

	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="test_test_id_seq", name="test_test_id_seq")
	@GeneratedValue(generator="test_test_id_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "TEST_ID", nullable = false)
	public int getTestId() {
		return this.testId;
	}

	public void setTestId(int testId) {
		this.testId = testId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUDENT_ID", nullable = false)
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "THEMES_ID")
	public Themes getThemes() {
		return this.themes;
	}

	public void setThemes(Themes themes) {
		this.themes = themes;
	}

	@Column(name = "TYPE_OF_TEST", nullable = false, length = 10)
	public String getTypeOfTest() {
		return this.typeOfTest;
	}

	public void setTypeOfTest(String typeOfTest) {
		this.typeOfTest = typeOfTest;
	}

	//@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIME_OF_TEST", nullable = false, length = 13)
	public Timestamp getTimeOfTest() {
		return this.timeOfTest;
	}

	public void setTimeOfTest(Timestamp timeOfTest) {
		this.timeOfTest = timeOfTest;
	}

	@Column(name = "MARK")
	public String getMark() {
		return this.mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}
	
	@Column(name = "ball", precision = 17, scale = 17)
	public Double getBall() {
		return this.ball;
	}

	public void setBall(Double ball) {
		this.ball = ball;
	}

}
