package beans;
// Generated 02.12.2013 21:28:10 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Themes generated by hbm2java
 */
@Entity
@Table(name = "themes", schema = "public")
public class Themes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7261336858886785940L;
	private int themeId;
	private Subjects subjects;
	private String nameOfTheme;
	private int numberOfHours;
	private String comment;
	private Set<Schedules> scheduleses = new HashSet<Schedules>(0);
	private Set<Tests> testses = new HashSet<Tests>(0);
	private Set<Questions> questionses = new HashSet<Questions>(0);

	public Themes() {
	}


	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="themes_theme_id_seq", name="themes_theme_id_seq")
	@GeneratedValue(generator="themes_theme_id_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "THEME_ID", nullable = false)
	public int getThemeId() {
		return this.themeId;
	}

	public void setThemeId(int themeId) {
		this.themeId = themeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBJECT_ID")
	public Subjects getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Subjects subjects) {
		this.subjects = subjects;
	}

	@Column(name = "NAME_OF_THEME", length = 40)
	public String getNameOfTheme() {
		return this.nameOfTheme;
	}

	public void setNameOfTheme(String nameOfTheme) {
		this.nameOfTheme = nameOfTheme;
	}

	@Column(name = "NUMBER_OF_HOURS", precision = 17, scale = 17)
	public int getNumberOfHours() {
		return this.numberOfHours;
	}

	public void setNumberOfHours(int numberOfHours) {
		this.numberOfHours = numberOfHours;
	}

	@Column(name = "comment", length = 40)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "themes")
	public Set<Schedules> getScheduleses() {
		return this.scheduleses;
	}

	public void setScheduleses(Set<Schedules> scheduleses) {
		this.scheduleses = scheduleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "themes")
	public Set<Tests> getTestses() {
		return this.testses;
	}

	public void setTestses(Set<Tests> testses) {
		this.testses = testses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "themes")
	public Set<Questions> getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set<Questions> questionses) {
		this.questionses = questionses;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return nameOfTheme;
	}

}
