package beans;
// Generated 02.12.2013 21:28:10 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TypeTeacher generated by hbm2java
 */
@Entity
@Table(name = "type_teacher", schema = "public")
public class TypeTeacher implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3025390450095318550L;
	private int typeTeachid;
	private String name;
	private Set<Teachers> teacherses = new HashSet<Teachers>(0);

	public TypeTeacher() {
	}

	public TypeTeacher(int typeTeachid, String name) {
		this.typeTeachid = typeTeachid;
		this.name = name;
	}

	public TypeTeacher(int typeTeachid, String name, Set<Teachers> teacherses) {
		this.typeTeachid = typeTeachid;
		this.name = name;
		this.teacherses = teacherses;
	}

	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="type_teacher_type_teachid_seq", name="type_teacher_type_teachid_seq")
	@GeneratedValue(generator="type_teacher_type_teachid_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "TYPE_TEACHID", nullable = false)
	public int getTypeTeachid() {
		return this.typeTeachid;
	}

	public void setTypeTeachid(int typeTeachid) {
		this.typeTeachid = typeTeachid;
	}

	@Column(name = "NAME", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeTeacher")
	public Set<Teachers> getTeacherses() {
		return this.teacherses;
	}

	public void setTeacherses(Set<Teachers> teacherses) {
		this.teacherses = teacherses;
	}

}
