package beans;
// Generated 02.12.2013 21:28:10 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TypeEducation generated by hbm2java
 */
@Entity
@Table(name = "type_education", schema = "public")
public class TypeEducation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7136976027965010975L;
	private int typeEducationId;
	private String name;
	private Set<Students> studentses = new HashSet<Students>(0);
	private Set<Teachers> teacherses = new HashSet<Teachers>(0);

	public TypeEducation() {
	}

	public TypeEducation(int typeEducationId, String name) {
		this.typeEducationId = typeEducationId;
		this.name = name;
	}

	public TypeEducation(int typeEducationId, String name,
			Set<Students> studentses, Set<Teachers> teacherses) {
		this.typeEducationId = typeEducationId;
		this.name = name;
		this.studentses = studentses;
		this.teacherses = teacherses;
	}

	@SequenceGenerator(allocationSize=1, initialValue=1, sequenceName="type_education_type_education_id_seq", name="type_education_type_education_id_seq")
	@GeneratedValue(generator="type_education_type_education_id_seq", strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name = "TYPE_EDUCATION_ID", nullable = false)
	public int getTypeEducationId() {
		return this.typeEducationId;
	}

	public void setTypeEducationId(int typeEducationId) {
		this.typeEducationId = typeEducationId;
	}

	@Column(name = "NAME", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeEducation")
	public Set<Students> getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set<Students> studentses) {
		this.studentses = studentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeEducation")
	public Set<Teachers> getTeacherses() {
		return this.teacherses;
	}

	public void setTeacherses(Set<Teachers> teacherses) {
		this.teacherses = teacherses;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return name;
	}

}
